env: dev

app_project: gosoline
app_family: sqlh
app_group: examples
app_name: simple

httpserver:
  default:
    port: 8081
    mode: release

sqlc:
  default:
    driver: mysql
    uri:
      host: localhost
      user: root
      password: gosoline
      database: examples
    migrations:
      enabled: true
      path: build/migrations
